/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/app/**/*.{js,jsx}',
    './src/components/**/*.{js,jsx}',
    './src/content/**/*.{js,jsx}',
    './src/lib/**/*.{js,jsx}',
  ],
  safelist: [
    'active',
    'open',
    'revealed',
    'visible',
    'bg-gold',
    'text-wood-dark',
    'bg-gold/10',
    'text-gold',
    'border-gold/20',
    'bg-blood/10',
    'text-blood-light',
    'border-blood/20',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#ffdbc9',
        'on-tertiary-fixed': '#002201',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#ffb68d',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#f2dfd5',
        'on-primary-container': '#fffbff',
        surface: '#fff8f6',
        'on-tertiary-container': '#f8fff0',
        'surface-container': '#feeae0',
        secondary: '#705d00',
        'inverse-surface': '#3a2e28',
        'on-secondary-container': '#6e5c00',
        'surface-container-low': '#fff1eb',
        'on-background': '#231914',
        background: '#fff8f6',
        'on-secondary-fixed': '#221b00',
        'surface-bright': '#fff8f6',
        'secondary-container': '#fcd400',
        'inverse-on-surface': '#ffede5',
        'on-secondary-fixed-variant': '#544600',
        'error-container': '#ffdad6',
        'inverse-primary': '#ffb68d',
        'secondary-fixed-dim': '#e9c400',
        'surface-container-high': '#f8e4db',
        'surface-tint': '#9a4600',
        primary: '#974400',
        'on-primary-fixed': '#321200',
        'tertiary-fixed-dim': '#77dd6a',
        'on-surface': '#231914',
        'secondary-fixed': '#ffe16d',
        'surface-variant': '#f2dfd5',
        'on-secondary': '#ffffff',
        tertiary: '#006c0c',
        'on-error-container': '#93000a',
        'on-surface-variant': '#564338',
        'primary-container': '#bb5808',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'outline-variant': '#ddc1b3',
        'surface-dim': '#ead6cd',
        'tertiary-container': '#1c871e',
        'on-tertiary-fixed-variant': '#005307',
        'on-primary-fixed-variant': '#763400',
        'tertiary-fixed': '#92fa83',
        outline: '#8a7266',
        'surface-container-lowest': '#ffffff',
        oro: '#FFB81C',
        azul: '#00247D',
        rojo: '#C8102E',
        blanco: '#F9F9F9',
        chocolate: '#1A0F00',
        wood: '#2c1810',
        'wood-light': '#5c3a28',
        'wood-dark': '#0f0906',
        gold: '#c8a84e',
        'gold-dim': '#a8883a',
        'gold-pale': '#e8d48e',
        linen: '#f5efe6',
        'linen-dim': '#d4c8b8',
        'linen-pale': '#faf6f0',
        blood: '#7a1e1e',
        'blood-light': '#a83232',
        'blood-bright': '#d44242',
        charcoal: '#1a1410',
        'charcoal-light': '#2a221e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'container-max': '1280px',
        unit: '8px',
        gutter: '24px',
        'margin-desktop': '40px',
      },
      fontFamily: {
        'boarding-pass-title': ['Space Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'label-caps': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'display-lg': ['Montserrat', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        display: ['Playfair Display', 'serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        mono: ['Space Grotesk', 'monospace'],
        script: ['Caveat', 'cursive'],
        uncial: ['Uncial Antiqua', 'serif'],
      },
      fontSize: {
        'boarding-pass-title': ['14px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '1', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '0', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-15px)' },
        },
        'pulse-gold': {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(255, 184, 28, 0.4)' },
          '50%': { boxShadow: '0 0 0 15px rgba(255, 184, 28, 0)' },
        },
        steam: {
          '0%, 100%': { transform: 'translateY(0) scale(1)', opacity: '0.4' },
          '50%': { transform: 'translateY(-25px) scale(1.3)', opacity: '0.08' },
        },
        glowPulse: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(200,168,78,0.15)' },
          '50%': { boxShadow: '0 0 50px rgba(200,168,78,0.3)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '0.6' },
          '50%': { opacity: '1' },
        },
        fadeRise: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
        'pulse-gold': 'pulse-gold 2s ease-in-out infinite',
        steam: 'steam 4s ease-in-out infinite',
        glow: 'glowPulse 3s ease-in-out infinite',
        'pulse-soft': 'pulseSoft 4s ease-in-out infinite',
        'fade-rise': 'fadeRise 0.8s ease-out forwards',
        'fade-rise-delay': 'fadeRise 0.8s ease-out 0.2s forwards',
        'fade-rise-delay-2': 'fadeRise 0.8s ease-out 0.4s forwards',
      },
    },
  },
  plugins: [],
};
